sudo: required
dist: trusty

language: scala
scala: 2.11.7
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - sudo bash setupVagrant.sh

script:
  # We preserve the environment to ensure the CODACY_PROJECT_TOKEN is accessible inside the containers
  - sudo --preserve-env bash test.sh